import Head from "next/head";

export default function Home() {
  const breakTheWorld = () => {
    throw new Error("Oh no you broke the world! You are bad!");
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <button
          onClick={breakTheWorld}
          className="bg-black text-white p-4 font-bold"
        >
          Break the world
        </button>
      </main>
    </div>
  );
}
